version: '3.5'

services:
  onlyoffice:
    image: 186184848/documentserver
    container_name: onlyoffice
    # restart: always
    ports:
      - 9997:80
      - 9998:8000
    environment:
      - JWT_SECRET=faber@JWT#1256
    volumes:
      - './data:/data'
