version: '3.3'
services:
  onlyoffice:
    image: 'onlyoffice/documentserver:7.3'
    container_name: onlyoffice-documentserver
    # restart: always
    ports:
      - '8081:80'
    environment:
      - JWT_SECRET=faber@JWT#1256
    volumes:
      - './data:/data'
    # command: 'redis-server --requirepass fa@redis#1276'
    networks:
      - onlyoffice

networks:
  onlyoffice:
    driver: bridge
