bootstrap.servers=kafka0:9092,kafka1:9092,kafka2:9092
group.id=test-consumer-group
enable.auto.commit=true
auto.commit.interval.ms=1000
auto.offset.reset=earliest
fetch.min.bytes=1
fetch.max.wait.ms=500
client.id=kafka2-test-consumer
