services:

  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    restart: always
    ports:
      - "8080:8080"
    #environment:
      #- MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./data:/label-studio/data
