services:
  clickhouse:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    volumes:
      - ./workspace:/opt/cloudbeaver/workspace
    restart: always
    #extra_hosts:
      #- "dwardserver1.dward.cn:172.17.0.1"
    dns:
     - 8.8.8.8
     - 8.8.4.4
