version: '3.5'

services:
  tdengine:
    image: 'tdengine/tdengine:3.3.0.0'
    container_name: tdengine
    restart: always
    ports:
      - 6030:6030
      - 6041:6041
      - 6030-6040:6030-6040/udp
    volumes:
      - './log:/var/log/taos'
      - './data:/var/lib/taos'
    environment:
      - TZ=Asia/Shanghai
