version: '3.5'

services:
  kodbox:
    image: kodcloud/kodbox
    container_name: kodbox
    restart: always
    ports:
      - 8080:80
    environment:
      TZ: Asia/Shanghai
    volumes:
      - "./site:/var/www/html"      #./site是站点目录位置，可以修改
    dns:
     - 8.8.8.8
     - 8.8.4.4

  kodoffice:
    image: kodcloud/kodoffice:7.4.1.1
    container_name: kodoffice
    restart: always
    ports:
      - 8090:80
    dns:
     - 8.8.8.8
     - 8.8.4.4