# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - '2181:2181'
      - '18080:8080'
    volumes:
      - './data/zookeeper:/bitnami/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka

  # zkui:
  #   image: qnib/zkui:latest
  #   ports:
  #     - '9090:9090'
  #   environment:
  #     - ZKUI_ZK_SERVER=zookeeper:2181
  #   depends_on:
  #     - zookeeper
  #   networks:
  #     - kafka

  kafka0:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    volumes:
      - './data/kafka:/bitnami/kafka'
      - './logs/kafka:/tmp/kafka_mounts/logs'
      - './config/kafka/consumer.properties:/opt/bitnami/kafka/config/consumer.properties'
      # - './config/kafka/server.properties:/bitnami/kafka/config/server.properties'
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=0
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://0.0.0.0:9093
      # 如果从别的主机连接kafka，请将localhost改成docker的宿主机IP
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka0:9092,EXTERNAL://192.168.31.127:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LOG_DIRS=/tmp/kafka_mounts/logs
    networks:
      - kafka

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka0
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: kafka0
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:9092
    # volumes:
    #   - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml
    networks:
      - kafka

networks:
  kafka:
    driver: bridge

volumes:
  kafka_data:
    driver: local